version: "3.8"

services:
  springboot-app-single:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-tester-single
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
