appli:
  version: 1.0.0


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  ## http://localhost:8080/actuator/beans    
    beans:
      enabled: true  


spring:
  devtools:
    restart:
      enabled: true
      #additional-paths: ../springboot-tester-exposition/src/main/java,../springboot-tester-application/src/main/java,../springboot-tester-domain/src/main/java,../springboot-tester-exposition/target/classes,../springboot-tester-application/target/classes,../springboot-tester-domain/target/classes
      additional-paths: ../springboot-tester-exposition/target/classes,../springboot-tester-application/target/classes,../springboot-tester-domain/target/classes
      exclude: static/**,public/**

      log-condition-evaluation-delta: true

# src/main/resources/application.yml
logging:
  file:
    name: logs/app.log      

# application.yml (dans le module exposition)
spring:
  config:
    import:
      - classpath:infrastructure-config.yml    